In [69]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

movie_genres = pd.read_csv('movie_reviews/movie_genres.csv')
user_reviews = pd.read_csv('movie_reviews/user_reviews.csv')

In [70]:
movie_genres

,Unnamed: 0,movie_title,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,...,genre_mystery,genre_news,genre_reality-tv,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
0,0,The Net,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
1,1,Happily N'Ever After,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,Tomorrowland,1,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,3,American Hero,1,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,4,Das Boot,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,Big Fish,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1996,1996,Get Real,0,0,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1997,1997,Trading Places,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1998,1998,DOA: Dead or Alive,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999,1999,Hey Arnold! The Movie,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
user_reviews

,Unnamed: 0,User,The Net,Happily N'Ever After,Tomorrowland,American Hero,Das Boot,Final Destination 3,Licence to Kill,The Hundred-Foot Journey,...,The Martian,Micmacs,Solomon and Sheba,In the Company of Men,Silent House,Big Fish,Get Real,Trading Places,DOA: Dead or Alive,Hey Arnold! The Movie
0,0,Vincent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,Edgar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Addilyn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,Marlee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,Javier,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,595,Mariana,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
596,596,Ivy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
597,597,Kevin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
598,598,Nora,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
599,599,Sarai,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [72]:
user_reviews.drop(['Unnamed: 0','User'], axis=1, inplace=True)
user_reviews.columns = [i for i in range(0,2000)]
user_reviews

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
598,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
599,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [73]:
genre = [g for g in list(movie_genres.columns) if 'genre' in g]
movie_repr = movie_genres[genre]
movie_repr

,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,...,genre_mystery,genre_news,genre_reality-tv,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
0,1,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,0,1,0,0
1,0,1,1,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
3,1,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,1,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1996,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1997,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1998,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999,0,1,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
def genre_distance(movie1_repr, movie2_repr):
    return np.sum(np.abs(movie1_repr - movie2_repr))

# Initialize an empty distance matrix
num_movies = movie_repr.shape[0]
distance_matrix = np.zeros((num_movies, num_movies))

# Compute the distance between each pair of movies
for i in range(num_movies):
    for j in range(i, num_movies):
        distance = genre_distance(movie_repr.iloc[i].values, movie_repr.iloc[j].values)
        distance_matrix[i, j] = distance
        distance_matrix[j, i] = distance

distance_matrix

array([[ 0., 10.,  6., ...,  6.,  5.,  9.],
       [10.,  0.,  6., ...,  4.,  5.,  1.],
       [ 6.,  6.,  0., ...,  6.,  3.,  5.],
       ...,
       [ 6.,  4.,  6., ...,  0.,  3.,  3.],
       [ 5.,  5.,  3., ...,  3.,  0.,  4.],
       [ 9.,  1.,  5., ...,  3.,  4.,  0.]], shape=(2000, 2000))

In [38]:
distance_matrix = np.abs(movie_repr.values[:, np.newaxis] - movie_repr.values).sum(axis=2)

mean_distance = np.mean(distance_matrix)
max_distance = np.max(distance_matrix)
min_distance = np.min(distance_matrix)
print(mean_distance, max_distance, min_distance)

distance_matrix

4.283252 14 0

array([[ 0, 10,  6, ...,  6,  5,  9],
       [10,  0,  6, ...,  4,  5,  1],
       [ 6,  6,  0, ...,  6,  3,  5],
       ...,
       [ 6,  4,  6, ...,  0,  3,  3],
       [ 5,  5,  3, ...,  3,  0,  4],
       [ 9,  1,  5, ...,  3,  4,  0]], shape=(2000, 2000))

In [74]:
# Compute Jaccard distance matrix efficiently
A = movie_repr.values[:, np.newaxis]  
B = movie_repr.values

# Compute intersection and union
intersection = np.logical_and(A, B).sum(axis=2)
union = np.logical_or(A, B).sum(axis=2)

# Compute Jaccard similarity)
distance_matrix = (intersection / np.maximum(union, 1))  # Avoid division by zero


mean_distance = np.mean(distance_matrix)
max_distance = np.max(distance_matrix)
min_distance = np.min(distance_matrix)
print(mean_distance, max_distance, min_distance)



distance_matrix

0.16836332127317152 1.0 0.0

array([[1.        , 0.        , 0.25      , ..., 0.        , 0.16666667,
        0.        ],
       [0.        , 1.        , 0.25      , ..., 0.2       , 0.16666667,
        0.8       ],
       [0.25      , 0.25      , 1.        , ..., 0.        , 0.4       ,
        0.28571429],
       ...,
       [0.        , 0.2       , 0.        , ..., 1.        , 0.        ,
        0.25      ],
       [0.16666667, 0.16666667, 0.4       , ..., 0.        , 1.        ,
        0.2       ],
       [0.        , 0.8       , 0.28571429, ..., 0.25      , 0.2       ,
        1.        ]], shape=(2000, 2000))

In [78]:
neigh_distance = 0.2

def get_nearest_movies(movie_id, neigh_distance):
    mask = distance_matrix[movie_id] >= neigh_distance
    output = np.where(np.array(mask) == 1)[0].tolist()
    return output, len(output)

output, length = get_nearest_movies(18, neigh_distance)
output, length

([3,
  4,
  7,
  10,
  12,
  13,
  14,
  16,
  18,
  19,
  22,
  23,
  24,
  25,
  27,
  29,
  30,
  31,
  34,
  35,
  36,
  38,
  40,
  42,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  55,
  57,
  58,
  59,
  60,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  72,
  73,
  74,
  76,
  79,
  80,
  81,
  84,
  85,
  86,
  87,
  89,
  92,
  93,
  96,
  97,
  99,
  100,
  101,
  105,
  106,
  107,
  110,
  111,
  114,
  117,
  119,
  121,
  123,
  124,
  125,
  127,
  128,
  129,
  134,
  136,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  147,
  149,
  150,
  151,
  152,
  154,
  157,
  159,
  160,
  161,
  163,
  164,
  166,
  167,
  168,
  173,
  174,
  176,
  184,
  185,
  187,
  189,
  191,
  192,
  193,
  195,
  196,
  198,
  199,
  200,
  202,
  204,
  206,
  209,
  213,
  216,
  220,
  221,
  222,
  224,
  225,
  228,
  231,
  233,
  236,
  237,
  238,
  239,
  242,
  245,
  248,
  249,
  253,
  254,
  256,
  258,
  259,
  261,
  263,
  264,
  265,
  267,
  270,
  271,
  277,
  281,
  282,
  287,
  288,
  290,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  301,
  303,
  306,
  309,
  310,
  311,
  313,
  315,
  317,
  318,
  320,
  322,
  324,
  325,
  326,
  327,
  328,
  330,
  333,
  335,
  340,
  341,
  342,
  343,
  344,
  345,
  348,
  352,
  354,
  355,
  357,
  358,
  359,
  361,
  362,
  364,
  366,
  367,
  369,
  372,
  373,
  375,
  380,
  381,
  382,
  386,
  387,
  388,
  389,
  391,
  393,
  396,
  398,
  399,
  401,
  402,
  406,
  407,
  409,
  410,
  414,
  417,
  419,
  423,
  424,
  425,
  426,
  427,
  430,
  432,
  434,
  435,
  436,
  437,
  439,
  440,
  443,
  445,
  446,
  448,
  449,
  450,
  453,
  454,
  457,
  458,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  470,
  471,
  473,
  474,
  476,
  477,
  481,
  485,
  486,
  488,
  489,
  490,
  491,
  493,
  497,
  499,
  501,
  502,
  503,
  504,
  505,
  506,
  510,
  513,
  515,
  516,
  517,
  518,
  521,
  524,
  525,
  527,
  531,
  533,
  537,
  540,
  541,
  544,
  545,
  546,
  550,
  551,
  552,
  554,
  555,
  558,
  562,
  565,
  566,
  569,
  570,
  572,
  573,
  578,
  580,
  583,
  586,
  588,
  589,
  590,
  593,
  594,
  597,
  598,
  599,
  605,
  608,
  609,
  613,
  616,
  617,
  618,
  621,
  623,
  627,
  629,
  631,
  633,
  634,
  636,
  638,
  639,
  641,
  642,
  644,
  646,
  647,
  648,
  649,
  650,
  654,
  655,
  659,
  660,
  661,
  666,
  667,
  669,
  671,
  672,
  676,
  679,
  683,
  684,
  685,
  687,
  688,
  692,
  693,
  694,
  695,
  698,
  701,
  703,
  704,
  705,
  706,
  707,
  709,
  711,
  714,
  716,
  718,
  720,
  721,
  722,
  725,
  730,
  732,
  733,
  735,
  737,
  738,
  740,
  741,
  743,
  744,
  747,
  748,
  749,
  750,
  751,
  753,
  754,
  755,
  756,
  757,
  758,
  760,
  761,
  764,
  765,
  769,
  771,
  772,
  773,
  780,
  783,
  785,
  786,
  789,
  791,
  792,
  799,
  800,
  803,
  805,
  808,
  809,
  811,
  813,
  815,
  816,
  819,
  821,
  822,
  824,
  825,
  828,
  830,
  833,
  834,
  836,
  837,
  839,
  840,
  842,
  846,
  847,
  848,
  849,
  851,
  854,
  856,
  857,
  858,
  860,
  862,
  864,
  868,
  869,
  872,
  873,
  876,
  877,
  878,
  879,
  881,
  882,
  883,
  884,
  886,
  888,
  889,
  892,
  896,
  898,
  901,
  902,
  903,
  905,
  906,
  907,
  908,
  909,
  912,
  913,
  915,
  916,
  917,
  918,
  921,
  923,
  926,
  928,
  929,
  930,
  931,
  932,
  936,
  939,
  941,
  944,
  946,
  949,
  950,
  951,
  953,
  961,
  962,
  963,
  964,
  966,
  968,
  969,
  971,
  973,
  974,
  976,
  979,
  980,
  981,
  982,
  983,
  985,
  990,
  991,
  992,
  993,
  994,
  996,
  999,
  1000,
  1001,
  1003,
  1005,
  1008,
  1009,
  1011,
  1012,
  1013,
  1015,
  1017,
  1018,
  1019,
  1020,
  1021,
  1026,
  1028,
  1029,
  1031,
  1033,
  1036,
  1037,
  1038,
  1045,
  1046,
  1048,
  1052,
  1053,
  1055,
  1056,
  1057,
  1060,
  1062,
  1063,
  1064,
  1065,
  1066,
  1070,
  1073,
  1074,
  1075,
  1076,
  1077,
  1078,
  1080,
  1081,
  1086,
  1087,
  1088,
  1092,
  1093,
  1094,
  1096,
  1097,
  1099,
  1101,
  1103,
  1104,
  1107,
  1108,
  1109,
  1111,
  1114,
  1117,
  1122,
  1123,
  1124,
  1125,
  1126,
  1128,
  1129,
  1130,
  1131,
  1132,
  1133,
  1135,
  1138,
  1140,
  1141,
  1143,
  1144,
  1145,
  1146,
  1147,
  1148,
  1151,
  1152,
  1154,
  1155,
  1157,
  1159,
  1161,
  1163,
  1164,
  1166,
  1168,
  1169,
  1170,
  1172,
  1173,
  1174,
  1175,
  1176,
  1177,
  1178,
  1181,
  1182,
  1183,
  1184,
  1185,
  1187,
  1188,
  1189,
  1191,
  1192,
  1193,
  1194,
  1195,
  1196,
  1197,
  1199,
  1200,
  1204,
  1207,
  1208,
  1209,
  1211,
  1212,
  1215,
  1220,
  1223,
  1224,
  1225,
  1226,
  1227,
  1228,
  1229,
  1232,
  1233,
  1235,
  1236,
  1237,
  1238,
  1239,
  1241,
  1242,
  1243,
  1245,
  1246,
  1248,
  1249,
  1253,
  1257,
  1260,
  1261,
  1263,
  1264,
  1266,
  1267,
  1268,
  1272,
  1273,
  1275,
  1279,
  1282,
  1284,
  1285,
  1286,
  1287,
  1288,
  1291,
  1292,
  1293,
  1294,
  1295,
  1296,
  1297,
  1299,
  1300,
  1302,
  1304,
  1305,
  1310,
  1312,
  1313,
  1315,
  1317,
  1318,
  1320,
  1321,
  1322,
  1323,
  1324,
  1325,
  1327,
  1328,
  1329,
  1331,
  1333,
  1334,
  1335,
  1337,
  1339,
  1345,
  1346,
  1351,
  1354,
  1356,
  1357,
  1360,
  1361,
  1363,
  1366,
  1368,
  1370,
  1371,
  1381,
  1383,
  1384,
  1386,
  1388,
  1391,
  1392,
  1393,
  1395,
  1396,
  1397,
  1399,
  1401,
  1405,
  1406,
  1407,
  1408,
  1412,
  1413,
  1415,
  1416,
  1419,
  1420,
  1424,
  1426,
  1429,
  1430,
  1431,
  1432,
  1433,
  1434,
  1435,
  1436,
  1438,
  1440,
  1441,
  1442,
  1443,
  1447,
  1448,
  1449,
  1450,
  1453,
  1454,
  1456,
  1458,
  1467,
  1470,
  1472,
  1475,
  1477,
  1478,
  1479,
  1480,
  1481,
  1485,
  1486,
  1488,
  1489,
  1490,
  1491,
  1493,
  1494,
  1497,
  1501,
  1502,
  1503,
  1504,
  1505,
  1506,
  1507,
  1508,
  1511,
  1514,
  1518,
  1520,
  1522,
  1525,
  1526,
  1531,
  1535,
  1536,
  1537,
  1539,
  1540,
  1541,
  1542,
  1543,
  1546,
  1547,
  1548,
  1549,
  1550,
  1551,
  1552,
  1553,
  1554,
  1555,
  1556,
  1559,
  1560,
  1561,
  1562,
  1565,
  1567,
  1570,
  1573,
  1574,
  1577,
  1578,
  1579,
  1584,
  1588,
  1589,
  1590,
  1591,
  1592,
  1594,
  1595,
  1600,
  1602,
  1606,
  1609,
  1610,
  1611,
  1612,
  1614,
  1617,
  1621,
  1622,
  1623,
  1624,
  1625,
  1626,
  1627,
  1630,
  1631,
  1633,
  1634,
  1641,
  1643,
  1644,
  1645,
  1647,
  1649,
  1653,
  1654,
  1655,
  1657,
  1659,
  1661,
  1663,
  1665,
  1668,
  1669,
  1670,
  1672,
  1673,
  1675,
  1676,
  1678,
  1680,
  1682,
  1683,
  1686,
  1687,
  1688,
  1689,
  1690,
  1691,
  1692,
  1694,
  1698,
  1700,
  1703,
  1705,
  1706,
  1707,
  1710,
  1711,
  1712,
  1714,
  1715,
  1717,
  1720,
  1723,
  1724,
  1726,
  1727,
  1731,
  1732,
  1736,
  1738,
  1739,
  1740,
  1743,
  1745,
  1746,
  1748,
  1751,
  1752,
  1753,
  1754,
  1757,
  1758,
  1759,
  1762,
  1763,
  1764,
  1765,
  1767,
  1769,
  1771,
  1776,
  1778,
  1779,
  1780,
  1781,
  1782,
  1783,
  1786,
  1788,
  1792,
  1794,
  1796,
  1798,
  1799,
  1800,
  1802,
  1804,
  1808,
  1810,
  1812,
  1813,
  1814,
  1815,
  1819,
  1820,
  1821,
  1822,
  1823,
  1825,
  1827,
  1828,
  1829,
  1830,
  1831,
  1832,
  1833,
  1835,
  1836,
  ...],
 1092)

In [ ]:
user = 0

candidate_movies = user_reviews.columns[user_reviews.iloc[user] == 0].tolist()
b_u = user_reviews.replace(0, np.nan).mean(axis=0).tolist()
estimated_ratings = {}

for movie_id in candidate_movies:
    output, length = get_nearest_movies(movie_id, neigh_distance)
    N_u = [movie for movie in output if user_reviews.iloc[user, movie] > 0]
    

    if len(N_u) > 0:
        
        estimated_ratings[movie_id] = b_u[movie_id] + np.sum([distance_matrix[movie_id, movie] * (user_reviews.iloc[user, movie] - b_u[movie]) for movie in N_u]) / np.sum([distance_matrix[movie_id, movie] for movie in N_u])
    
    else:

        estimated_ratings[movie_id] = b_u[movie_id]

In [90]:


user = 0

# Get candidate movies (movies not rated by the user)
candidate_movies = user_reviews.columns[user_reviews.iloc[user] == 0].to_numpy()

# Compute user-specific bias (replace 0s with NaN before computing mean)
b_u = np.nanmean(user_reviews.replace(0, np.nan), axis=0)

# Dictionary to store estimated ratings
estimated_ratings = {}

# Convert user_reviews to NumPy array for fast indexing
user_ratings = user_reviews.to_numpy()

for movie_id in candidate_movies:
    output, _ = get_nearest_movies(movie_id, neigh_distance)
    
    # Find neighbors that the user has rated
    N_u = np.array([movie for movie in output if user_ratings[user, movie] > 0])

    if N_u.size > 0:
        # Compute weighted sum using NumPy's optimized operations
        numerator = np.dot(distance_matrix[movie_id, N_u], (user_ratings[user, N_u] - b_u[N_u]))
        denominator = np.sum(distance_matrix[movie_id, N_u])

        estimated_ratings[movie_id] = b_u[movie_id] + (numerator / denominator if denominator != 0 else 0)
    else:
        estimated_ratings[movie_id] = b_u[movie_id]  # Default to baseline if no neighbors exist

In [95]:
len(estimated_ratings.keys())

1961

In [98]:
user_ratings[0,user_ratings[0] == 0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(1961,))